### ISSUE TITLE
Extension throws errors and doesn't show/hide fields in simple test

### ISSUE THREAD

**Issue by danieljwestman** [MiniDigger/directus-conditional-fields#5]
macOS Big Sur (M1)
Directus 9.0.0-rc.61
PG 12
Node v15.14.0

--

I've setup a very simple test of this conditional-fields extension. One toggle that _should_ show/hide a text field. It's not working. When I'm about to update an item in the collection I get the following error immediately.  

```
Vue warn]: Invalid prop: type check failed for prop "conditions". Expected , got Array 

found in

---> <InterfaceGoConditionalFields>
       <FormFieldInterface> at src/components/v-form/form-field-interface.vue
         <FormField> at src/components/v-form/form-field.vue
           <VForm> at src/components/v-form/v-form.vue
             <PrivateView> at src/views/private/private-view.vue
               <CollectionsItem> at src/modules/collections/routes/item.vue
                 <App> at src/app.vue
                   <Root>
```

Nothing happens with the fields when clicking the toggle. More errors:

```
[Vue warn]: Error in callback for watcher "$parent.$parent.$parent.values": "TypeError: Cannot read property 'forEach' of undefined"

found in

---> <InterfaceGoConditionalFields>
       <FormFieldInterface> at src/components/v-form/form-field-interface.vue
         <FormField> at src/components/v-form/form-field.vue
           <VForm> at src/components/v-form/v-form.vue
             <PrivateView> at src/views/private/private-view.vue
               <CollectionsItem> at src/modules/collections/routes/item.vue
                 <App> at src/app.vue
                   <Root>
```

Any known issues with this extension?

**Comment by uebmaster** [comment]
> macOS Big Sur (M1)
> Directus 9.0.0-rc.61
> PG 12
> Node v15.14.0
> 
> --
> 
> I've setup a very simple test of this conditional-fields extension. One toggle that _should_ show/hide a text field. It's not working. When I'm about to update an item in the collection I get the following error immediately.
> 
> ```
> Vue warn]: Invalid prop: type check failed for prop "conditions". Expected , got Array 
> 
> found in
> 
> ---> <InterfaceGoConditionalFields>
>        <FormFieldInterface> at src/components/v-form/form-field-interface.vue
>          <FormField> at src/components/v-form/form-field.vue
>            <VForm> at src/components/v-form/v-form.vue
>              <PrivateView> at src/views/private/private-view.vue
>                <CollectionsItem> at src/modules/collections/routes/item.vue
>                  <App> at src/app.vue
>                    <Root>
> ```
> 
> Nothing happens with the fields when clicking the toggle. More errors:
> 
> ```
> [Vue warn]: Error in callback for watcher "$parent.$parent.$parent.values": "TypeError: Cannot read property 'forEach' of undefined"
> 
> found in
> 
> ---> <InterfaceGoConditionalFields>
>        <FormFieldInterface> at src/components/v-form/form-field-interface.vue
>          <FormField> at src/components/v-form/form-field.vue
>            <VForm> at src/components/v-form/v-form.vue
>              <PrivateView> at src/views/private/private-view.vue
>                <CollectionsItem> at src/modules/collections/routes/item.vue
>                  <App> at src/app.vue
>                    <Root>
> ```
> 
> Any known issues with this extension?

Same case for me.

Ubuntu Server 20.04
Directus 9.0.0-rc.69
PG 12
Node v14.16.1

Even doesn't show the global toggle for show/hide the fields

**Comment by SalahAdDin** [comment]
@MiniDigger Any advance on this? Thank you

**Comment by MiniDigger** [comment]
@SalahAdDin the feature this plugin provides inspired the conditionals feature in directus, which is a much better impl of this idea. this repo is archived, according to the readme, I just never hit the archive button it seems, lol
ill do that now, if you have any questions feel free to reach out to me on the directus discord.
